- releases/rstudio.json
rstudio:ds-r4.2.3 -> rstudio:r4.2.3
> Update rstudio.json to delete ds prefix in image rstudio tag

- .github/workflows/main-workflow-template.yml
- .github/workflows/main-workflow.yml
- releases/base.json
- releases/jupyter-pyspark.json
- releases/jupyter-python.json
- releases/jupyter-pytorch.json
- releases/jupyter-r.json
- releases/jupyter-tensorflow.json
- releases/pyspark.json
- releases/python-datascience.json
- releases/python-minimal.json
- releases/python-pytorch.json
- releases/python-tensorflow.json
- releases/r-datascience.json
- releases/r-minimal.json
- releases/rstudio-sparkr.json
- releases/rstudio.json
- releases/sparkr.json
- releases/vscode-pyspark.json
- releases/vscode-python.json
- releases/vscode-pytorch.json
- releases/vscode-tensorflow.json
> Modify build pipeline to use Docker build/push action instead of artifacts

- .github/workflows/main-workflow.yml
- dev/build-chain.py
- releases/base.json
Required to properly use Tensorflow and PyTorch using GPU.
> Use devel version of nvidia/cuda image

- r-datascience/Dockerfile
- r-minimal/Dockerfile
- spark/Dockerfile
Put essential packages for use with Onyxia (connect to S3, Vault) in r-minimal instead of r-datascience. Also takes into account the changes suggested in #76
> Put essential packages in R minimal

- base/Dockerfile
> adding kubectl krew plugin to base image

- scripts/onyxia-init.sh
Adding a non sudo version to add env variable in .bashrc and R when the user can't do sudo
> add non sudo alternative for vault injection

- .github/workflows/main-workflow-template.yml
- .github/workflows/security-workflow.yml
- base/Dockerfile
- jupyter/Dockerfile
- python-datascience/Dockerfile
- python-minimal/Dockerfile
- python-pytorch/Dockerfile
- python-tensorflow/Dockerfile
- r-datascience/Dockerfile
- r-minimal/Dockerfile
- r-python-julia/Dockerfile
- rstudio/Dockerfile
- spark/Dockerfile
- vscode/Dockerfile
Add labels to Dockerfile to indicate maintainer & contact info
> Add labels to images

- vscode/Dockerfile
> add an extension to run observable notebook in vscode

- base/Dockerfile
- scripts/install-argo-workflows-cli.sh
- scripts/install-duckdb-cli.sh
- scripts/install-helm.sh
- scripts/install-kubectl-krew.sh
- scripts/install-kubectl.sh
- scripts/install-mc.sh
- scripts/install-postgresql-cli.sh
- scripts/install-system-libs.sh
- scripts/install-vault-cli.sh
> Fix postgresql client versions mismatch & refactor base script

- .github/workflows/main-workflow.yml
- .github/workflows/pull-request-workflow.yml
- .gitignore
- python-minimal/Dockerfile
3.10.12 -> 3.10.13
3.11.4 -> 3.11.6
> Bump patch versions for Python 3.10 and 3.11

- vscode/settings/User.json
On m'a dit que c'était plus d'actualité d'avoir des linter max-line < 100 @avouacr
> increase flake max line length default value

- r-datascience/Dockerfile
- scripts/install-quarto.sh
> feat(r): install tinytex via quarto

- .github/workflows/main-workflow-template.yml
So that our catalog can work on Apple Sillicon an RaspberryPi
> Cross compile for ARM and x86

- .github/workflows/main-workflow.yml
- releases/vscode-r.json
- vscode/Dockerfile
- vscode/settings/User.json
A new image with a tailored vscode with respect to developping R code.
The generation of the docker image has been tested (and should work), but please bear in mind the completion of user settings for vscode may have some side effects on the r-julia-python minimalistic image.
> Add r-vscode

- scripts/install-spark-hadoop-hive.sh
- spark/Dockerfile
> Update Spark with Java 17

- vscode/Dockerfile
Tout est dans le titre @avouacr
> add ltex extension in vscode for grammar/spell check (Latex/qmd/markdown

- base/tests.yaml
- jupyter/tests.yaml
- python-datascience/tests.yaml
- python-minimal/tests.yaml
- python-pytorch/tests.yaml
- python-tensorflow/tests.yaml
- r-datascience/tests.yaml
- r-minimal/tests.yaml
- r-python-julia/tests.yaml
- rstudio/tests.yaml
- spark/tests.yaml
- vscode/tests.yaml
Added this test in all tests.yaml to make sure duckdb's binary existed:
```yaml
- name: "Does the binary exists?"
command: "which"
args: ["duckdb"]
expectedOutput: ["/usr/local/bin/duckdb"]
```
> test that bin duckdb exist

- scripts/onyxia-init.sh
> Use RStudio config file to pass theme instead of R hooks

- .github/workflows/main-workflow.yml
- .github/workflows/pull-request-workflow.yml
- 3.11.8 -> 3.11.9
- 3.12.2 -> 3.12.3
close #133
> chore(deps): upgrade Python versions

- .github/workflows/main-workflow.yml
- .github/workflows/pull-request-workflow.yml
- python-minimal/Dockerfile
- r-minimal/Dockerfile
- Python : 3.12.2 -> 3.12.4
- R : 4.4.0 -> 4.4.1
close #210 
close #211
> chore(deps): bump Python & R versions

- .github/workflows/main-workflow.yml
- python-minimal/Dockerfile
Version 3.12.6 was not available from conda-forge:
https://anaconda.org/conda-forge/python/files?version=3.12.6
> Updated python to version 3.12.5

- base/scripts/fix-user-permissions.sh
- base/scripts/onyxia-init.sh
This reverts commit 5bd8a3c64f496f8f43629263f6ae239f1ac3b4de.
> Revert "fix(onxyia-init): give relevant user permissions (#257)"

- python-datascience/scripts/install-geospatial-python.sh
fix https://github.com/InseeFrLab/images-datascience/issues/267
> fix geospatial

- base/scripts/onyxia-init.sh
> Removed PROJECT_USER and PROJECT_GROUP env variables in onyxia-init.sh

- base/scripts/onyxia-init.sh
- base/scripts/onyxia-set-repositories.sh
- jupyter/scripts/install-jupyterlab.sh
- r-datascience/scripts/install-java.sh
- spark/scripts/install-java.sh
> Redirect all command -v outputs to /dev/null

- vscode/scripts/install-vscode-extensions.sh
> [vscode] Install and setup R kernel for jupyter-notebooks

- base/scripts/install-duckdb-extensions.sh
> Install duckdb icu extension
